### ISSUE TITLE
Explore Astro

### ISSUE THREAD

**Issue by banuragaxioned** [axioned/codex#12]
- [ ] Get a general understanding of what [Astro](https://astro.build/) is (their [Docs](https://docs.astro.build/) is a great place to start
- [ ] Use Tailwind CSS where necessary
- [ ] Complete their [tutorial](https://docs.astro.build/en/tutorial/0-introduction/) in your own repo
- [ ] Deploy that tutorial to something like Vercel or Netlify
- [ ] Review [Astro Islands](https://docs.astro.build/en/concepts/islands/)

**Comment by ahsanaaxioned** [comment]
Done With This and sub topics are:

- What is Astro
- Installation of Astro
- Astro Components
- How to Implimet tailwind with Astro
- Folder structure in Astro
- Markdown/Mdx with Astro
- Advantages and why of Astro
- Astro Islanding architecture

Blog page repo link and deploy preview link using Astro and implimented with tailwinds are below

Here Is The Repo Link: https://github.com/ahsanaaxioned/BlogPage-Using-Astro

Here Is The Netlify Deploy Link: https://blogpage-using-astro.netlify.app/
