### ISSUE TITLE
Understand and get familiar with Tailwind CSS

### ISSUE THREAD

**Issue by banuragaxioned** [axioned/codex#13]
- [ ] Watch https://www.youtube.com/watch?v=mr15Xzb1Ook
- [ ] Spend a few hours looking at and getting familiar with their [docs](https://tailwindcss.com/docs/)

**Comment by ahsanaaxioned** [comment]
Done with Tailwind CSS and here is some Sub-Topics are below:

- What is tailwind & how its different from other CSS frameworks
- How to install tailwind
- tailwind configuration
- VS code extension for tailwind CSS intellisense
- Different utility Tailwind classes for element such as font,margin,padding,border,flex,etc.
- Square bracket notation for custom styling.
- Media query in tailwind and how to overwrite it using configure object.
- Hover/Focus and other state mode in tailwind
- Apply directive in tailwind
- Layer directive in tailwind
- When we used apply and layer directive in tailwind
- how to customize tailwind CSS
