### ISSUE TITLE
Get familiar with Typescript

### ISSUE THREAD

**Issue by banuragaxioned** [axioned/codex#14]
We'll use it in the project. We might not go overboard with al the rules, but we'll be using Astro's recommended settings (which is already in the `main` branch). So try and get a bit familiar wit hthis.

**Comment by ahsanaaxioned** [comment]
Done With This And Subtopics Are Below:

- What is type Script
- How to install
- What is difference between Type Script & Java Script
- Syntax of Type Script
- Advantages of Type Script
- Aliases in Type Script
- How to create custom Type Aliases
- Interface in Type Script
- difference between Aliases and Interface
- How to add Two different Aliaases
- How to extend one interface to another
- Props in Type Script
