### ISSUE TITLE
Markdown/Authoring Content and Content Collections

### ISSUE THREAD

**Issue by banuragaxioned** [axioned/codex#15]
- [ ] [Working with Markdown/MDX](https://docs.astro.build/en/guides/content/)
- [ ] [Content Collections](https://docs.astro.build/en/guides/content/)

**Comment by ahsanaaxioned** [comment]
Done with this and subtopics are below

- Writing content
- Markdown Authoring
- MDX Authoring
- Managing content pages
- Supported page files

Content Collection subtopics are below

- what is content collection
- What are Content Collections?
- Organizing with multiple collections
- Defining Collections
- Defining a collection schema
- Defining multiple collections
- Using third-party collection schemas.
